# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-11 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irc', '0004_auto_20160711_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioparar',
            name='ID_BOT',
            field=models.CharField(max_length=100),
        ),
    ]
