# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-14 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irc', '0005_auto_20160711_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOT_INFO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_CONVERS', models.CharField(max_length=100)),
                ('ID_BOT', models.CharField(max_length=100)),
                ('INICIO', models.DateTimeField(auto_now_add=True)),
                ('ULTIMA', models.DateTimeField(auto_now_add=True)),
                ('CANAL', models.CharField(max_length=100)),
                ('EVENTOS', models.IntegerField()),
                ('NUM_MSG', models.IntegerField()),
                ('ESTADO', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EVENTOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_EVENT', models.CharField(max_length=100)),
                ('FECHA', models.DateTimeField(auto_now_add=True)),
                ('CANAL', models.CharField(max_length=100)),
                ('SERVIDOR', models.CharField(max_length=100)),
                ('PATRON', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MENSAJES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_MSG', models.CharField(max_length=100)),
                ('FECHA', models.DateTimeField(auto_now_add=True)),
                ('CANAL', models.CharField(max_length=100)),
                ('SERVIDOR', models.CharField(max_length=100)),
                ('USUARIO', models.CharField(max_length=100)),
                ('MENSAJE', models.CharField(max_length=1000)),
            ],
        ),
    ]
